apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tempconverter-mysql
  labels:
    app: mysql
spec:
  serviceName: tempconverter-mysql-service
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: "{{ .Values.mysqlImage.repository }}:{{ .Values.mysqlImage.tag }}"
        imagePullPolicy: {{ .Values.mysqlImage.pullPolicy }}
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: "true"
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: {{ include "tempconverter.fullname" . }}-mysql-secret
              key: mysql-database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "tempconverter.fullname" . }}-mysql-secret
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "tempconverter.fullname" . }}-mysql-secret
              key: mysql-password
