apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tempconverter.fullname" . }}-mysql-secret
  labels:
    {{- include "tempconverter.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-database: {{ .Values.mysql.database | b64enc | quote }}
  mysql-user: {{ .Values.mysql.user | b64enc | quote }}
  mysql-password: {{ .Values.mysql.password | b64enc | quote }}