apiVersion: v1
kind: Service
metadata:
  name: {{ include "tempconverter.fullname" . }}-mysql-service
  labels:
    {{- include "tempconverter.labels" . | nindent 4 }}
spec:
#  type: {{ .Values.service.type }}
  ports:
    - port: 3306
      protocol: TCP
      name: mysql
  selector:
    app: mysql
